# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import time

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import QTextEdit, QApplication, QMainWindow
from PyQt6.QtCore import pyqtSignal, QTimer
from PyQt6.QtGui import QTextCursor


class Terminal(QTextEdit):
    """QTextEdit, который сам себе file-like объект: write()/flush()
    как у sys.stdout, но текст рендерится прямо в этом же виджете."""
 
    _text_written = pyqtSignal(str)
 
    def __init__(self, parent=None, redirect_stdout=True, redirect_stderr=False):
        super().__init__(parent)
        self.setReadOnly(True)
        self._text_written.connect(self._append)
        
        self.setReadOnly(True)
        self.setFrameStyle(QtWidgets.QFrame.Shape.NoFrame)
 
        self._old_stdout = None
        self._old_stderr = None
 
        if redirect_stdout:
            self._old_stdout = sys.stdout
            sys.stdout = self
        if redirect_stderr:
            self._old_stderr = sys.stderr
            sys.stderr = self
 
    # --- файлоподобный интерфейс ---
    def write(self, text):
        self._text_written.emit(str(text))
 
    def flush(self):
        pass
 
    def restore(self):
        """Вернуть исходные sys.stdout/sys.stderr."""
        if self._old_stdout is not None:
            sys.stdout = self._old_stdout
        if self._old_stderr is not None:
            sys.stderr = self._old_stderr
 
    def closeEvent(self, event):
        self.restore()
        super().closeEvent(event)
 
    # --- рендер с поддержкой \r (перезапись строки) ---
    def _append(self, text):
        text = text.replace('\r\n', '\n')
 
        cursor = self.textCursor()
        cursor.movePosition(QTextCursor.MoveOperation.End)
 
        while '\r' in text:
            before, text = text.split('\r', 1)
            if before:
                cursor.insertText(before)
            # выделяем от текущей позиции до начала строки и удаляем —
            # это и есть "перезапись" строки, как в реальном терминале
            cursor.movePosition(
                QTextCursor.MoveOperation.StartOfLine,
                QTextCursor.MoveMode.KeepAnchor
            )
            cursor.removeSelectedText()
 
        if text:
            cursor.insertText(text)
 
        self.setTextCursor(cursor)
        self.ensureCursorVisible()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Q3V#1D")
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setContentsMargins(0, 0, 0, 0)      
        self.launch_2 = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.launch_2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.launch_2.setObjectName("launch_2")
        self.launch_1 = QtWidgets.QWidget()
        self.launch_1.setObjectName("launch")
        self.pushButton = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton.setGeometry(QtCore.QRect(230, 370, 371, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 170, 371, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 80, 371, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 260, 371, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.launch_2.addTab(self.launch_1, "")
        self.mod_repo = QtWidgets.QWidget()
        self.mod_repo.setObjectName("mod_repo")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.mod_repo)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 780, 570))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.mod_repo)
        self.verticalScrollBar.setGeometry(QtCore.QRect(780, -1, 15, 570))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.launch_2.addTab(self.mod_repo, "")

        self.terminal = Terminal(parent=self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.terminal.setContentsMargins(0, 0, 0, 0)
        self.terminal.hide()
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.launch_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.launch_2.setTabText(self.launch_2.indexOf(self.launch_1), _translate("MainWindow", "launch"))
        self.launch_2.setTabText(self.launch_2.indexOf(self.mod_repo), _translate("MainWindow", "mods"))
        MainWindow.setWindowTitle(_translate("MainWindow", "Q3V#1D"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))
        self.pushButton_2.setText(_translate("MainWindow", "Connect metarena"))
        self.pushButton_3.setText(_translate("MainWindow", "Connect meat"))
        self.pushButton_4.setText(_translate("MainWindow", "q3a.space"))

if __name__ == "__main__":

    class MainWindow(QMainWindow, Ui_MainWindow):
        def __init__(self):
            super().__init__()
            self.setupUi(self)
            self._center_on_screen()

            self.pushButton.clicked.connect(self.launch)

        def _center_on_screen(self):
            screen = QApplication.primaryScreen()
            screen_geometry = screen.availableGeometry()
            window_geometry = self.frameGeometry()
            window_geometry.moveCenter(screen_geometry.center())
            self.move(window_geometry.topLeft())
        
        def launch(self):
            self.open_terminal()
            print("Launch clicked")
            QTimer.singleShot(1000, self.close_terminal)
        
        def open_terminal(self):
            self.terminal.raise_()
            self.terminal.show()
            self.setFixedSize(800, 400)

        def close_terminal(self):
            self.setFixedSize(800, 600)
            self.terminal.hide()

    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
