# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from base_methods import *

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import QTextEdit, QApplication, QMainWindow
from PyQt6.QtCore import pyqtSignal, QTimer
from PyQt6.QtGui import QTextCursor, QPixmap, QPalette, QBrush, QPainter, QColor


DARK_STYLE = """
QWidget {
    background-color: #2b2b2b;
    color: #ffffff;
    font-family: Arial;
    font-size: 11pt;
}

QPushButton {
    background-color: #3c3c3c;
    color: #ffffff;
    border: 1px solid #555555;
    border-radius: 4px;
    padding: 6px;
}

QPushButton:hover {
    background-color: #4a4a4a;
}

QPushButton:pressed {
    background-color: #2a2a2a;
}

QPushButton:disabled {
    background-color: #262626;
    color: #808080;
}

QTabWidget::pane {
    border: 0px;
}

QTabBar::tab {
    background-color: #3c3c3c;
    color: #ffffff;
    padding: 8px 16px;
}

QTabBar::tab:selected {
    background-color: #505050;
}

QTableWidget {
    background-color: #2b2b2b;
    color: #ffffff;
    gridline-color: #555555;
}

QHeaderView::section {
    background-color: #3c3c3c;
    color: #ffffff;
    padding: 4px;
    border: 1px solid #555555;
}

QScrollBar:vertical {
    background: #2b2b2b;
    width: 12px;
    margin: 0px;
}

QScrollBar::handle:vertical {
    background: #555555;
    border-radius: 6px;
    min-height: 20px;
}
"""

def load_cover_pixmap(path, target_w, target_h):
    pixmap = QtGui.QPixmap(path)
    scaled = pixmap.scaled(
        target_w, target_h,
        QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
        QtCore.Qt.TransformationMode.SmoothTransformation
    )
    x = (scaled.width() - target_w) // 2
    y = (scaled.height() - target_h) // 2
    return scaled.copy(x, y, target_w, target_h)

class Terminal(QTextEdit):
    """QTextEdit, который сам себе file-like объект: write()/flush()
    как у sys.stdout, но текст рендерится прямо в этом же виджете."""

    _text_written = pyqtSignal(str)

    def __init__(self, parent=None, redirect_stdout=True, redirect_stderr=False,
                 background_path=None, darken=0, text_color="#000000"):
        super().__init__(parent)
        self.setReadOnly(True)
        self.setFrameStyle(QtWidgets.QFrame.Shape.NoFrame)
        self.document().setDocumentMargin(0)
        self._text_written.connect(self._append)

        self._background_pixmap = QtGui.QPixmap(background_path) if background_path else None
        self._darken = darken

        # ВАЖНО: никакого background-image здесь — только прозрачность и цвет текста
        self.setStyleSheet(f"QTextEdit {{ background: transparent; color: {text_color}; border: 0px; }}")

        self._old_stdout = None
        self._old_stderr = None
        if redirect_stdout:
            self._old_stdout = sys.stdout
            sys.stdout = self
        if redirect_stderr:
            self._old_stderr = sys.stderr
            sys.stderr = self

    def scrollContentsBy(self, dx, dy):
        self.viewport().update()
        super().scrollContentsBy(dx, dy)

    def paintEvent(self, event):
        if self._background_pixmap and not self._background_pixmap.isNull():
            painter = QtGui.QPainter(self.viewport())
            vp = self.viewport().size()
            scaled = self._background_pixmap.scaled(
                vp,
                QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
                QtCore.Qt.TransformationMode.SmoothTransformation
            )
            x = (scaled.width() - vp.width()) // 2
            y = (scaled.height() - vp.height()) // 2
            painter.drawPixmap(0, 0, scaled, x, y, vp.width(), vp.height())
            painter.fillRect(self.viewport().rect(), QtGui.QColor(0, 0, 0, self._darken))
            painter.end()
        super().paintEvent(event)

    def write(self, text):
        self._text_written.emit(str(text))

    def flush(self):
        pass

    def restore(self):
        if self._old_stdout is not None:
            sys.stdout = self._old_stdout
        if self._old_stderr is not None:
            sys.stderr = self._old_stderr

    def closeEvent(self, event):
        self.restore()
        super().closeEvent(event)

    def _append(self, text):
        text = text.replace('\r\n', '\n')
        cursor = self.textCursor()
        cursor.movePosition(QTextCursor.MoveOperation.End)
        while '\r' in text:
            before, text = text.split('\r', 1)
            if before:
                cursor.insertText(before)
            cursor.movePosition(
                QTextCursor.MoveOperation.StartOfLine,
                QTextCursor.MoveMode.KeepAnchor
            )
            cursor.removeSelectedText()
        if text:
            cursor.insertText(text)
        self.setTextCursor(cursor)
        self.ensureCursorVisible()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Q3V#1D")
        MainWindow.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setContentsMargins(0, 0, 0, 0)
        
        self.launch_2 = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.launch_2.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.launch_2.setObjectName("launch_2")
        self.launch_2.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.launch_1 = QtWidgets.QWidget()
        self.launch_1.setObjectName("launch")
        self.launch_2.addTab(self.launch_1, "")
        self.mod_repo = QtWidgets.QWidget()
        self.mod_repo.setObjectName("mod_repo")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.mod_repo)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 850, 600))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.mod_repo)
        self.verticalScrollBar.setGeometry(QtCore.QRect(850, -1, 15, 600))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.launch_2.addTab(self.mod_repo, "")

        # terminal
        self.terminal = Terminal(
            parent=self.centralwidget,
            background_path='./icons/back.jpg',
            darken=140,
            text_color='#ffffff'
        )
        self.terminal.setGeometry(QtCore.QRect(0, 0, 800, 400))
        self.terminal.setContentsMargins(0, 0, 0, 0)
        self.terminal.hide()

        # launcher
        self.label_logo = QtWidgets.QLabel(parent=self.launch_1)
        self.label_logo.setGeometry(QtCore.QRect(0, 0, 875, 600))  # подберите координаты
        pixmap = QPixmap("./icons/back.jpg")
        self.label_logo.setPixmap(pixmap)
        self.label_logo.setObjectName("label_logo")
        self.label_logo.setPixmap(load_cover_pixmap(
            './icons/back.jpg', 875, 600
        ))
        self.pushButton = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton.setGeometry(QtCore.QRect(630, 500, 200, 60))
        self.pushButton.setObjectName("pushButton")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.launch_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_close = QtWidgets.QPushButton("×", parent=self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(875, 0, 25, 25))
        self.pushButton_close.clicked.connect(self.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.launch_2.setTabText(self.launch_2.indexOf(self.launch_1), _translate("MainWindow", "launch"))
        self.launch_2.setTabText(self.launch_2.indexOf(self.mod_repo), _translate("MainWindow", "mods"))
        MainWindow.setWindowTitle(_translate("MainWindow", "Q3V#1D"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))

        
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self._center_on_screen()

        self.pushButton.clicked.connect(self.launch)

    def _center_on_screen(self):
        screen = QApplication.primaryScreen()
        screen_geometry = screen.availableGeometry()
        window_geometry = self.frameGeometry()
        window_geometry.moveCenter(screen_geometry.center())
        self.move(window_geometry.topLeft())
    
    def launch(self):
        launch()
        self.close()
    
    def open_terminal(self):
        self.terminal.raise_()
        self.terminal.show()
        self.setFixedSize(800, 400)

    def close_terminal(self):
        self.setFixedSize(900, 600)
        self.terminal.hide()

if __name__ == "__main__":

    app = QApplication(sys.argv)
    app.setStyleSheet(DARK_STYLE)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
