# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from PyQt6.QtWidgets import QTextEdit, QApplication, QMainWindow
from PyQt6.QtCore import pyqtSignal, QTimer
from PyQt6.QtGui import QTextCursor, QPixmap, QPalette, QBrush, QPainter, QColor

from base_methods import *
from upd_tools import *
from bmods_tools import *


def load_tab_icon(path, size=32, counter_rotate=90):
    pixmap = QtGui.QPixmap(path).scaled(
        size, size,
        QtCore.Qt.AspectRatioMode.KeepAspectRatio,
        QtCore.Qt.TransformationMode.SmoothTransformation
    )
    transform = QtGui.QTransform().rotate(counter_rotate)
    return QtGui.QIcon(pixmap.transformed(transform, QtCore.Qt.TransformationMode.SmoothTransformation))


with open('./ui/style.css', 'r') as f:
    DARK_STYLE = f.read()

def load_cover_pixmap(path, target_w, target_h):
    pixmap = QtGui.QPixmap(path)
    scaled = pixmap.scaled(
        target_w, target_h,
        QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
        QtCore.Qt.TransformationMode.SmoothTransformation
    )
    x = (scaled.width() - target_w) // 2
    y = (scaled.height() - target_h) // 2
    return scaled.copy(x, y, target_w, target_h)

def make_rotated_tab_icon(icon_path, angle=90, icon_size=28, tab_size=60):
    pixmap = QPixmap(icon_path).scaled(
        icon_size, icon_size,
        Qt.AspectRatioMode.KeepAspectRatio,
        Qt.TransformationMode.SmoothTransformation
    )
    rotated = pixmap.transformed(
        QTransform().rotate(angle),
        Qt.TransformationMode.SmoothTransformation
    )

    label = QLabel()
    label.setPixmap(rotated)
    label.setFixedSize(tab_size, tab_size)   # размер = размеру вкладки
    label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    return label


class ToastNotification(QtWidgets.QWidget):
    """Всплывающее уведомление поверх содержимого окна.

    Это НЕ отдельное системное окно (в отличие от QMessageBox) — обычный
    дочерний виджет поверх centralwidget, который сам анимированно
    выезжает сверху, держится duration мс и плавно исчезает. Несколько
    уведомлений подряд складываются в стек друг под другом.

    Использование:
        ToastNotification.show_error(self.centralwidget, "Не удалось подключиться к серверу")
        ToastNotification.show_warning(self.centralwidget, "Соединение нестабильно")
        ToastNotification.show_info(self.centralwidget, "Список модов обновлён")
    """

    _active_toasts = []  # общий для класса стек показанных уведомлений

    LEVEL_COLORS = {
        "error":   "#e74c3c",
        "warning": "#f1c40f",
        "info":    "#3498db",
        "success": "#2ecc71",
    }

    def __init__(self, parent, message, level="error", duration=4000, width=320):
        super().__init__(parent)
        self._duration = duration
        self._width = width

        self._build_ui(message, level)
        self._install_effects()
        self._position()

        ToastNotification._active_toasts.append(self)
        self.show()
        self._animate_in()
        QtCore.QTimer.singleShot(self._duration, self._animate_out)

    # ---------- построение внешнего вида ----------

    def _build_ui(self, message, level):
        color = self.LEVEL_COLORS.get(level, self.LEVEL_COLORS["info"])
        self.setFixedWidth(self._width)

        self.setStyleSheet(f'''
            QWidget#toastBody {{
                background-color: rgba(30, 30, 30, 235);
                border-left: 4px solid {color};
                border-radius: 8px;
            }}
            QLabel {{
                color: #ffffff;
                background: transparent;
            }}
            QPushButton {{
                color: #aaaaaa;
                background: transparent;
                border: none;
                font-weight: bold;
            }}
            QPushButton:hover {{
                color: #ffffff;
            }}
        ''')

        outer = QtWidgets.QHBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)

        body = QtWidgets.QWidget(self)
        body.setObjectName("toastBody")
        body_layout = QtWidgets.QHBoxLayout(body)
        body_layout.setContentsMargins(12, 10, 8, 10)

        label = QtWidgets.QLabel(message, body)
        label.setWordWrap(True)
        body_layout.addWidget(label, 1)

        close_btn = QtWidgets.QPushButton("×", body)
        close_btn.setCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        close_btn.setFixedSize(18, 18)
        close_btn.clicked.connect(self._animate_out)
        body_layout.addWidget(close_btn, 0, QtCore.Qt.AlignmentFlag.AlignTop)

        outer.addWidget(body)
        self.adjustSize()

    def _install_effects(self):
        self._opacity_effect = QtWidgets.QGraphicsOpacityEffect(self)
        self._opacity_effect.setOpacity(0.0)
        self.setGraphicsEffect(self._opacity_effect)

        self._fade_anim = QtCore.QPropertyAnimation(self._opacity_effect, b"opacity")
        self._fade_anim.setDuration(200)

        self._slide_anim = QtCore.QPropertyAnimation(self, b"pos")
        self._slide_anim.setDuration(200)
        self._slide_anim.setEasingCurve(QtCore.QEasingCurve.Type.OutCubic)

    # ---------- позиционирование и стек ----------

    def _target_pos(self):
        """Место в правом верхнем углу родителя с учётом уже показанных
        уведомлений — каждое следующее встаёт ниже предыдущего."""
        parent_rect = self.parentWidget().rect()
        margin, spacing = 16, 8

        y = margin
        for toast in ToastNotification._active_toasts:
            if toast is self:
                continue
            y += toast.height() + spacing

        x = parent_rect.width() - self._width - margin
        return QtCore.QPoint(x, y)

    def _position(self):
        target = self._target_pos()
        self.move(target.x(), target.y() - 20)  # старт чуть выше — для эффекта выезда
        self.raise_()

    # ---------- анимации появления/исчезновения ----------

    def _animate_in(self):
        target = self._target_pos()

        self._fade_anim.stop()
        self._fade_anim.setStartValue(0.0)
        self._fade_anim.setEndValue(1.0)
        self._fade_anim.start()

        self._slide_anim.stop()
        self._slide_anim.setStartValue(self.pos())
        self._slide_anim.setEndValue(target)
        self._slide_anim.start()

    def _animate_out(self):
        self._fade_anim.stop()
        self._fade_anim.setStartValue(self._opacity_effect.opacity())
        self._fade_anim.setEndValue(0.0)
        self._fade_anim.finished.connect(self._on_hidden)
        self._fade_anim.start()

    def _on_hidden(self):
        try:
            self._fade_anim.finished.disconnect(self._on_hidden)
        except TypeError:
            pass
        if self in ToastNotification._active_toasts:
            ToastNotification._active_toasts.remove(self)
        self._reflow_remaining()
        self.deleteLater()

    def _reflow_remaining(self):
        """После закрытия одного уведомления подтягивает оставшиеся вверх."""
        for toast in list(ToastNotification._active_toasts):
            anim = QtCore.QPropertyAnimation(toast, b"pos")
            anim.setDuration(150)
            anim.setEasingCurve(QtCore.QEasingCurve.Type.OutCubic)
            anim.setStartValue(toast.pos())
            anim.setEndValue(toast._target_pos())
            anim.start()
            toast._reflow_anim = anim  # держим ссылку, чтобы GC не убил анимацию раньше времени

    # ---------- удобные статические конструкторы ----------

    @staticmethod
    def show_error(parent, message, duration=4000):
        return ToastNotification(parent, message, level="error", duration=duration)

    @staticmethod
    def show_warning(parent, message, duration=4000):
        return ToastNotification(parent, message, level="warning", duration=duration)

    @staticmethod
    def show_info(parent, message, duration=3000):
        return ToastNotification(parent, message, level="info", duration=duration)

    @staticmethod
    def show_success(parent, message, duration=3000):
        return ToastNotification(parent, message, level="success", duration=duration)


class DragHandle(QtWidgets.QWidget):
    """Тонкая затемнённая полоска сверху окна. У окна нет системного заголовка
    (FramelessWindowHint), поэтому таскать его можно только за эту полоску:
    зажали ЛКМ на ней — двигаем мышью — окно едет следом."""

    def __init__(self, parent=None, height=6, opacity=110):
        super().__init__(parent)
        self.setFixedHeight(height)
        self.setCursor(QtCore.Qt.CursorShape.SizeAllCursor)
        self.setStyleSheet(f"background-color: rgba(0, 0, 0, {opacity});")
        self._drag_offset = None

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.MouseButton.LeftButton:
            self._drag_offset = (
                event.globalPosition().toPoint() - self.window().frameGeometry().topLeft()
            )
            event.accept()

    def mouseMoveEvent(self, event):
        if self._drag_offset is not None and event.buttons() & QtCore.Qt.MouseButton.LeftButton:
            self.window().move(event.globalPosition().toPoint() - self._drag_offset)
            event.accept()

    def mouseReleaseEvent(self, event):
        self._drag_offset = None
        event.accept()


class Terminal(QTextEdit):
    """QTextEdit, который сам себе file-like объект: write()/flush()
    как у sys.stdout, но текст рендерится прямо в этом же виджете."""

    _text_written = pyqtSignal(str)

    def __init__(self, parent=None, redirect_stdout=True, redirect_stderr=False,
                 background_path=None, darken=0, text_color="#000000"):
        super().__init__(parent)
        self.setReadOnly(True)
        self.setFrameStyle(QtWidgets.QFrame.Shape.NoFrame)
        self.document().setDocumentMargin(0)
        self._text_written.connect(self._append)

        self._background_pixmap = QtGui.QPixmap(background_path) if background_path else None
        self._darken = darken

        # ВАЖНО: никакого background-image здесь — только прозрачность и цвет текста
        self.setStyleSheet(f"QTextEdit {{ background: transparent; color: {text_color}; border: 0px; }}")

        self._old_stdout = None
        self._old_stderr = None
        if redirect_stdout:
            self._old_stdout = sys.stdout
            sys.stdout = self
        if redirect_stderr:
            self._old_stderr = sys.stderr
            sys.stderr = self

    def scrollContentsBy(self, dx, dy):
        self.viewport().update()
        super().scrollContentsBy(dx, dy)

    def paintEvent(self, event):
        if self._background_pixmap and not self._background_pixmap.isNull():
            painter = QtGui.QPainter(self.viewport())
            vp = self.viewport().size()
            scaled = self._background_pixmap.scaled(
                vp,
                QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
                QtCore.Qt.TransformationMode.SmoothTransformation
            )
            x = (scaled.width() - vp.width()) // 2
            y = (scaled.height() - vp.height()) // 2
            painter.drawPixmap(0, 0, scaled, x, y, vp.width(), vp.height())
            painter.fillRect(self.viewport().rect(), QtGui.QColor(0, 0, 0, self._darken))
            painter.end()
        super().paintEvent(event)

    def write(self, text):
        self._text_written.emit(str(text))

    def flush(self):
        pass

    def restore(self):
        if self._old_stdout is not None:
            sys.stdout = self._old_stdout
        if self._old_stderr is not None:
            sys.stderr = self._old_stderr

    def closeEvent(self, event):
        self.restore()
        super().closeEvent(event)

    def _append(self, text):
        text = text.replace('\r\n', '\n')
        cursor = self.textCursor()
        cursor.movePosition(QTextCursor.MoveOperation.End)
        while '\r' in text:
            before, text = text.split('\r', 1)
            if before:
                cursor.insertText(before)
            cursor.movePosition(
                QTextCursor.MoveOperation.StartOfLine,
                QTextCursor.MoveMode.KeepAnchor
            )
            cursor.removeSelectedText()
        if text:
            cursor.insertText(text)
        self.setTextCursor(cursor)
        self.ensureCursorVisible()


class ModTableWidget(QtWidgets.QTableWidget):
    """Таблица модов (имя / описание / кнопка действия).

    Вся логика настройки колонок, добавления строк, заполнения по списку
    и очистки инкапсулирована здесь — снаружи достаточно вызывать
    populate()/add_mod_row()/clear_mods().

    background_path/darken — опциональная картинка фона под содержимым
    таблицы; рисуется в paintEvent поверх viewport, затемняется darken."""

    #: сигнал испускается при клике по кнопке в строке — (row, mod_name)
    mod_button_clicked = pyqtSignal(int, str)

    def __init__(self, parent=None, background_path=None, darken=0):
        super().__init__(parent)
        self.setObjectName("tableWidget")

        self._background_pixmap = QtGui.QPixmap(background_path) if background_path else None
        self._darken = darken

        self._setup_table()

    def _setup_table(self):
        self.setColumnCount(3)
        self.setHorizontalHeaderLabels(["Name", "Description", "Action"])

        header = self.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Fixed)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeMode.Fixed)
        self.setColumnWidth(0, 150)
        self.setColumnWidth(2, 110)

        self.verticalHeader().setVisible(False)
        self.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)

        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        # ВАЖНО: никакого background-image в стилях — фон рисуется в
        # paintEvent, тут только прозрачность, чтобы он был виден сквозь ячейки.
        self.setStyleSheet('''
            QTableWidget {
                background: transparent;
            }
            QTableWidget::item {
                background: transparent;
            }
        ''')

    def scrollContentsBy(self, dx, dy):
        # без этого QWidget::scroll() просто сдвигает уже отрисованные
        # пиксели и фоновая картинка «размазывается» при прокрутке
        self.viewport().update()
        super().scrollContentsBy(dx, dy)

    def paintEvent(self, event):
        if self._background_pixmap and not self._background_pixmap.isNull():
            painter = QtGui.QPainter(self.viewport())
            vp = self.viewport().size()
            scaled = self._background_pixmap.scaled(
                vp,
                QtCore.Qt.AspectRatioMode.KeepAspectRatioByExpanding,
                QtCore.Qt.TransformationMode.SmoothTransformation
            )
            x = (scaled.width() - vp.width()) // 2
            y = (scaled.height() - vp.height()) // 2
            painter.drawPixmap(0, 0, scaled, x, y, vp.width(), vp.height())
            painter.fillRect(self.viewport().rect(), QtGui.QColor(0, 0, 0, self._darken))
            painter.end()
        super().paintEvent(event)

    def add_mod_row(self, name, description, button_text="Установить", on_click=None, tooltip=None):
        """Добавляет одну строку: имя, описание и кнопку в 3-й колонке.
        tooltip — необязательный текст подсказки при наведении на строку
        (по умолчанию используется description).
        on_click(row) — колбэк на клик по кнопке; если не передан,
        используется self.on_mod_button_clicked (испускает mod_button_clicked)."""
        row = self.rowCount()
        self.insertRow(row)

        tip = tooltip if tooltip is not None else description

        name_item = QtWidgets.QTableWidgetItem(name)
        name_item.setToolTip(tip)
        self.setItem(row, 0, name_item)

        desc_item = QtWidgets.QTableWidgetItem(description)
        desc_item.setToolTip(tip)
        self.setItem(row, 1, desc_item)

        button = QtWidgets.QPushButton(button_text)
        button.setCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        button.setToolTip(tip)
        handler = on_click if on_click is not None else self.on_mod_button_clicked
        button.clicked.connect(lambda checked=False, r=row: handler(r))
        self.setCellWidget(row, 2, button)

        return row

    def populate(self, modlist, on_click=None):
        """Полностью пересобирает таблицу по словарю модов вида
        {name: {"description": ...}, ...}. Старое содержимое очищается."""
        self.clear_mods()
        for name, info in modlist.items():
            self.add_mod_row(
                name,
                info["description"],
                button_text="download" if name not in bmod_conf else "delete",
                on_click=on_click,
            )

    def clear_mods(self):
        """Полностью очищает таблицу от строк модов."""
        self.setRowCount(0)

    def on_mod_button_clicked(self, row):
        """Обработчик кнопки по умолчанию: печатает имя мода и
        испускает сигнал mod_button_clicked(row, mod_name)."""
        name_item = self.item(row, 0)
        mod_name = name_item.text() if name_item else f"row {row}"
        print(f"[mods] Кнопка нажата для: {mod_name}")
        self.mod_button_clicked.emit(row, mod_name)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Q3V#1D")
        MainWindow.setFixedSize(900, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setContentsMargins(0, 0, 0, 0)
        
        self.launch_2 = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.launch_2.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.launch_2.setObjectName("launch_2")
        self.launch_2.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.launch_1 = QtWidgets.QWidget()
        self.launch_1.setObjectName("launch")
        self.launch_2.addTab(self.launch_1, "")
        self.mod_repo = QtWidgets.QWidget()
        self.mod_repo.setObjectName("mod_repo")

        self.tableWidget = ModTableWidget(
            parent=self.mod_repo,
            background_path='./icons/back.jpg',
            darken=140
        )
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 850, 600))
        self.tableWidget.populate({})

        self.launch_2.addTab(self.mod_repo, "")

        # terminal
        self.terminal = Terminal(
            parent=self.centralwidget,
            background_path='./icons/back.jpg',
            darken=140,
            text_color='#ffffff'
        )
        self.terminal.setGeometry(QtCore.QRect(0, 0, 800, 400))
        self.terminal.setContentsMargins(0, 0, 0, 0)
        self.terminal.hide()

        # launcher
        self.label_logo = QtWidgets.QLabel(parent=self.launch_1)
        self.label_logo.setGeometry(QtCore.QRect(0, 0, 875, 600))  # подберите координаты
        pixmap = QPixmap("./icons/back.jpg")
        self.label_logo.setPixmap(pixmap)
        self.label_logo.setObjectName("label_logo")
        self.label_logo.setPixmap(load_cover_pixmap(
            './icons/back.jpg', 875, 600
        ))
        self.pushButton = QtWidgets.QPushButton(parent=self.launch_1)
        self.pushButton.setGeometry(QtCore.QRect(600, 500, 200, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton {border-radius: 30px}")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.launch_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # полоска для перетаскивания безрамочного окна (тянуть за верхний край)
        self.drag_handle = DragHandle(parent=self.centralwidget, height=25, opacity=110)
        self.drag_handle.setGeometry(QtCore.QRect(0, 0, 900, 6))
        self.drag_handle.raise_()

        self.pushButton_close = QtWidgets.QPushButton("×", parent=self.centralwidget)
        self.pushButton_close.setStyleSheet("QPushButton {color: #ff0000}")
        self.pushButton_close.clicked.connect(self.close)
        self.pushButton_close.raise_()
        self._init_close_button_hover()

    def _init_close_button_hover(self):
        """Кнопка закрытия по умолчанию спрятана за правым краем окна и
        выезжает наружу, когда курсор оказывается у верхнего правого угла."""
        self._close_hidden_geo = QtCore.QRect(900, 0, 25, 25)  # полностью за краем окна
        self._close_shown_geo = QtCore.QRect(875, 0, 25, 25)   # выехавшее положение
        self.pushButton_close.setGeometry(self._close_hidden_geo)

        self._close_anim = QtCore.QPropertyAnimation(self.pushButton_close, b"geometry")
        self._close_anim.setDuration(150)
        self._close_anim.setEasingCurve(QtCore.QEasingCurve.Type.OutCubic)

        self._close_visible = False
        # Наведение проверяем таймером, а не enterEvent/leaveEvent — так надёжнее,
        # потому что кнопка и полоска для драга перекрываются другими виджетами
        # (QTabWidget поверх всего окна), и события мыши могут не доходить.
        self._close_hover_zone = 40  # ширина/высота зоны у угла в пикселях
        self._hover_timer = QtCore.QTimer(self.centralwidget)
        self._hover_timer.setInterval(60)
        self._hover_timer.timeout.connect(self._check_close_hover)
        self._hover_timer.start()

    def _check_close_hover(self):
        pos = self.centralwidget.mapFromGlobal(QtGui.QCursor.pos())
        zone = self._close_hover_zone
        near_edge = (
            self.centralwidget.rect().contains(pos)
            and pos.x() >= self.centralwidget.width() - zone
            and pos.y() <= zone
        )
        if near_edge == self._close_visible:
            return
        self._close_visible = near_edge
        target = self._close_shown_geo if near_edge else self._close_hidden_geo
        self._close_anim.stop()
        self._close_anim.setStartValue(self.pushButton_close.geometry())
        self._close_anim.setEndValue(target)
        self._close_anim.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.launch_2.setTabIcon(self.launch_2.indexOf(self.launch_1), load_tab_icon("./icons/b3.png"))
        self.launch_2.setIconSize(QtCore.QSize(30, 30))
        self.launch_2.setTabText(self.launch_2.indexOf(self.mod_repo), _translate("MainWindow", "mods"))
        MainWindow.setWindowTitle(_translate("MainWindow", "Q3V#1D"))
        self.pushButton.setText(_translate("MainWindow", "Checking..."))
        self.pushButton.setEnabled(False)

        
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self._center_on_screen()

    def _center_on_screen(self):
        screen = QApplication.primaryScreen()
        screen_geometry = screen.availableGeometry()
        window_geometry = self.frameGeometry()
        window_geometry.moveCenter(screen_geometry.center())
        self.move(window_geometry.topLeft())
    
    def launch(self):
        launch()
        self.close()

    def qerror(self, error):
        ToastNotification.show_error(self.centralwidget, error)
        QTimer.singleShot(3000, self.close)
    
    def open_terminal(self):
        self.terminal.raise_()
        self.terminal.show()
        self.setFixedSize(800, 400)

    def close_terminal(self):
        self.setFixedSize(900, 600)
        self.terminal.hide()

    def closeEvent(self, a0: QtGui.QCloseEvent | None) -> None:
        try:
            shutil.rmtree("./temp_files/")
        except Exception:
            pass
        return super().closeEvent(a0)

    def upd_status(self, need_update):
        _translate = QtCore.QCoreApplication.translate
        if not os.path.exists('./temp_files/modlist.json'):
            self.tableWidget.populate({})
        else:
            self.tableWidget.populate(get_modlist())
        
        if need_update:
            self.pushButton.setText(_translate("MainWindow", "Update"))
            self.pushButton.setEnabled(True)
            self.pushButton.clicked.connect(self.start_update)
        else:
            self.pushButton.setText(_translate("MainWindow", "Launch"))
            self.pushButton.setEnabled(True)
            self.pushButton.clicked.connect(self.launch)

    class Update(QtCore.QThread):
        result_ready = QtCore.pyqtSignal(bool)

        def run(self):
            autoupdate()
            self.result_ready.emit(True)

    def start_update(self):
        self.open_terminal()
        self.update_thread = self.Update()
        self.update_thread.finished.connect(lambda: (self.close_terminal(), self.upd_status(False)))
        self.update_thread.start()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyleSheet(DARK_STYLE)
    window = MainWindow()
    window.show()
    QTimer.singleShot(4000, lambda: ToastNotification.show_warning(window, 'connection'))
    sys.exit(app.exec())
